### ISSUE TITLE
No such file or directory: 'xxx.enGOcmped.mcl.temp'

### ISSUE THREAD

**Issue by kelimeike** [Guannan-Wang/GOMCL#8]
Hi Guannan,

When running the GOMCL-sub test code (GOMCL-sub.py go-basic.obo Wendrich_PNAS_SD2_LR_TMO5_H_vs_L.clstr -C 1 -gosize 2000 -I 1.8 -ssd 0 -hg 0 -hgt -hm -nw),  I got the mistake that follows:

sh: 1: mcl: not found
Traceback (most recent call last):
  File "/vsphhome/kelimei/software/GOMCL/GOMCL-master/GOMCL-sub.py", line 83, in <module>
    subclstr_go_clstr_dict, subclstr_gene_clstr_dict, subclstr_clstred_go_dict, subclstr_clstred_gene_dict = go_assign_cluster(os.path.splitext(args.Clstr)[0] + "_GOsize" + str(args.gosize) + "_" + str(args.simindex) + "_Ct" + str(args.cutoff) + "I" + str(args.inflation) + "_C" + str(args.subclstr) + ".enGOfltrd", args.simindex, args.cutoff, args.inflation)
  File "/vsphhome/kelimei/software/GOMCL/GOMCL-master/scripts/go_clustering.py", line 126, in go_assign_cluster
    go_mclgroup_dict, gene_mclgroup_dict = go_clustering(enGOfmtfltr, SI, Ct, Inf)
  File "/vsphhome/kelimei/software/GOMCL/GOMCL-master/scripts/go_clustering.py", line 100, in go_clustering
    fin_mcl = open(os.path.splitext(enGOfmtfltr)[0] + "_" + str(SI) + "_Ct" + str(Ct) + "I" + str(Inf) + ".enGOcmped.mcl.temp","rU")
IOError: [Errno 2] No such file or directory: 'Wendrich_PNAS_SD2_LR_TMO5_H_vs_L_GOsize2000_OC_Ct0.5I1.8_C1_OC_Ct0.5I1.8.enGOcmped.mcl.temp'

I cannot find what went wrong. Can you help me to solve this problem?

thank you!
Limei

**Comment by kelimeike** [comment]
I tried to configure and make mcl but got errors:

collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:320: clmformat] Error 1
make[2]: Leaving directory '/vsphhome/kelimei/software/GOMCL/GOMCL-master/mcl-14-137/src/shcl'
make[1]: *** [Makefile:233: check-recursive] Error 1
make[1]: Leaving directory '/vsphhome/kelimei/software/GOMCL/GOMCL-master/mcl-14-137/src'
make: *** [Makefile:279: check-recursive] Error 1

Has anyone catch the same problems？

**Comment by Guannan-Wang** [comment]
Hello kelimeike,

Thanks for your interest in using GOMCL, and sorry for the late response. The problem you have is with MCL installation, could you please try to do it with anaconda, [similar to what is being described here](https://github.com/Guannan-Wang/GOMCL/issues/6#issuecomment-1269084173)?
Please let me know if your run into other issues.
Thanks.

Guannan
